"""Public nutrition specialist API."""

from slim_guard.agents.nutrition.agent import (
    CONSERVATIVE_ASSESSMENT_TEXT,
    DEFAULT_NUTRITION_PROMPT_VERSION,
    NUTRITION_AGENT_ALLOWED_TOOLS,
    NUTRITION_AGENT_PROMPT,
    ConservativeNutritionFallback,
    NutritionAgent,
    NutritionAssessmentValidator,
)
from slim_guard.agents.nutrition.constants import CONSULT_NUTRITION_TOOL_NAME
from slim_guard.agents.nutrition.context import NutritionContextCompiler
from slim_guard.agents.nutrition.contracts import (
    CalculationInput,
    CalculationObservation,
    CandidateRejectionReason,
    EvidenceAuthority,
    EvidencePacketInput,
    EvidencePacketLike,
    KnowledgeAdoptionStatus,
    KnowledgeCandidate,
    KnowledgeCorpusStatus,
    KnowledgeInput,
    KnowledgeRetrieval,
    NutritionAgentResult,
    NutritionContext,
    NutritionEvidence,
    NutritionValidationIssue,
    NutritionValidationIssueCode,
    NutritionValidationReport,
    RejectedKnowledgeCandidate,
)
from slim_guard.agents.nutrition.knowledge import (
    CitationValidationPolicy,
    CitationValidationReport,
    KnowledgeCandidateBinder,
    NutritionCitationValidator,
    NutritionKnowledgeRepositoryAdapter,
    bind_candidates,
)
from slim_guard.agents.nutrition.repair import (
    NutritionRepairRequest,
    NutritionRepairResult,
)
from slim_guard.agents.nutrition.specialist import (
    NutritionConsultationRequest,
    NutritionConsultationResult,
    NutritionSpecialist,
)
from slim_guard.agents.nutrition.tool import (
    ConsultNutritionArguments,
    NutritionAgentToolHandler,
    nutrition_agent_tool_definitions,
    nutrition_agent_tool_executors,
)

__all__ = [
    "CONSERVATIVE_ASSESSMENT_TEXT",
    "CONSULT_NUTRITION_TOOL_NAME",
    "CalculationInput",
    "CalculationObservation",
    "CandidateRejectionReason",
    "CitationValidationPolicy",
    "CitationValidationReport",
    "ConservativeNutritionFallback",
    "ConsultNutritionArguments",
    "EvidenceAuthority",
    "EvidencePacketInput",
    "EvidencePacketLike",
    "DEFAULT_NUTRITION_PROMPT_VERSION",
    "KnowledgeAdoptionStatus",
    "KnowledgeCorpusStatus",
    "KnowledgeCandidate",
    "KnowledgeCandidateBinder",
    "KnowledgeInput",
    "KnowledgeRetrieval",
    "NutritionAgent",
    "NutritionAgentToolHandler",
    "NutritionAgentResult",
    "NutritionConsultationRequest",
    "NutritionConsultationResult",
    "NutritionRepairRequest",
    "NutritionRepairResult",
    "NutritionCitationValidator",
    "NutritionKnowledgeRepositoryAdapter",
    "NutritionSpecialist",
    "NUTRITION_AGENT_ALLOWED_TOOLS",
    "NUTRITION_AGENT_PROMPT",
    "NutritionAssessmentValidator",
    "NutritionContext",
    "NutritionContextCompiler",
    "NutritionEvidence",
    "NutritionValidationIssue",
    "NutritionValidationIssueCode",
    "NutritionValidationReport",
    "RejectedKnowledgeCandidate",
    "bind_candidates",
    "nutrition_agent_tool_definitions",
    "nutrition_agent_tool_executors",
]
