"""Trainer depends on this durable job port, never ORM or private repositories."""

from typing import Any, Protocol


class BuildInterrupted(RuntimeError):
    """The worker lost its lease or the user cancelled the build."""


class BuildPort(Protocol):
    async def load(self, key: str) -> Any: ...
    async def save(self, key: str, value: Any, *, stage: str, message: str) -> None: ...
    async def event(self, stage: str, message: str, **details: Any) -> None: ...
    async def reserve_call(self, *, max_calls: int, max_tokens: int) -> dict[str, int]: ...
    async def record_tokens(self, tokens: int) -> None: ...
